config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  resources :books, only: [:new, :create, :show, :index, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      @book = Book.find(params[:id])
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h3>Eding Book</h3>
<%= form_with model: @book do |f| %>
  <div>Title</div>
    <%= f.text_field :title %>
  <div>Body</div>
    <%= f.text_area :body %>

  <div><%= f.submit 'Update Book' %></div>
<% end %>

<div>
  <%= link_to 'Show', book_path(@book) %>
  <span><%= link_to 'Back', books_path %></span>
</div>

app/views/books/index.html.erb
<h2>Books</h2>

<table>

  <thead>
    <th>Title</th>
    <th>Body</th>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book_path(book), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<h3>New Book</h3>
<%= form_with model: @book do |f| %>
  <div>Title</div>
    <%= f.text_field :title %>
  <div>Body</div>
    <%= f.text_area :body %>

  <div><%= f.submit 'Create Book' %></div>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div>Title: <%= @book.title %></div>
<div>Body: <%= @book.body %></div>

<div>
  <%= link_to 'Edit', edit_book_path(@book) %>
  <span><%= link_to 'Back', books_path %></span>
</div>

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や印象を共有し交換することができます</p>

app/views/layouts/_header.html.erb
<h4>各リンク先(仮設置)</h4>
<%= link_to 'トップページ', root_path %>
<%= link_to '投稿一覧', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><%= render 'layouts/header' %></header>
    <%= yield %>
  </body>
</html>